"""Captured model reports — the empirical record behind bench + probe.

One JSON file per model+quant under `reports/`. `spark llm bench --save` fills
the `speed` section and `spark llm probe --save` fills `capability`; each updates
the same file in place (seeded from templates/report.example.json) so the two
measurements accumulate into a single per-model report with shared provenance
(source repo, quant, footprint, engine build). `render_markdown()` turns the JSON
set into the table humans read in docs/benchmarks.md.

A user's own runs land in reports/ (gitignored); reports/reference/ is the
committed reference set. Pure stdlib — no third-party deps.
"""

from __future__ import annotations

import json
import re
import time
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
REPORTS_DIR = REPO_ROOT / "reports"
SKELETON = REPO_ROOT / "templates" / "report.example.json"


def today() -> str:
    return time.strftime("%Y-%m-%d")


def slug(name: str, quant: str | None) -> str:
    s = f"{name}-{quant}" if quant else name
    return re.sub(r"[^A-Za-z0-9._-]+", "-", s).strip("-")


def default_path(name: str, quant: str | None) -> Path:
    return REPORTS_DIR / f"{slug(name, quant)}.json"


def _seed() -> dict:
    if SKELETON.exists():
        try:
            return json.loads(SKELETON.read_text())
        except (json.JSONDecodeError, OSError):
            pass
    return {}


def load(path: Path) -> dict:
    if path.exists():
        try:
            return json.loads(path.read_text())
        except (json.JSONDecodeError, OSError):
            pass
    return _seed()


def update(path: Path, *, provenance: dict | None = None,
           speed: dict | None = None, capability: dict | None = None) -> dict:
    """Merge measured sections into the per-model report at `path`, in place.

    Only non-null provenance fields overwrite; `speed`/`capability` replace their
    whole section when provided, so the other section is preserved across runs.
    """
    data = load(path)
    data.pop("_comment", None)   # don't carry the skeleton's comment into outputs
    if provenance:
        for k, v in provenance.items():
            if v is not None:
                data[k] = v
    if speed is not None:
        data["speed"] = speed
    if capability is not None:
        data["capability"] = capability
    data["updated"] = today()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2) + "\n")
    return data


def collect(directory: Path | None = None) -> list[dict]:
    """Load every report JSON under `directory` (recurses into reference/).

    Each row is tagged `_src` ("reference" or "local") so dedupe can prefer a
    user's own run over the committed reference copy on a tie.
    """
    base = directory or REPORTS_DIR
    out = []
    if not base.exists():
        return out
    for p in sorted(base.rglob("*.json")):
        try:
            d = json.loads(p.read_text())
        except (json.JSONDecodeError, OSError):
            continue
        d["_src"] = "reference" if "reference" in p.relative_to(base).parts else "local"
        out.append(d)
    return out


def _dedupe(rows: list[dict]) -> list[dict]:
    """Collapse reports for the same model+quant. Prefer the newer `updated`
    date; on a tie prefer a user's own run over the committed reference copy."""
    def rank(d):
        return (d.get("updated") or "", 0 if d.get("_src") == "reference" else 1)
    best: dict = {}
    for d in rows:
        key = ((d.get("model") or "").lower(), (d.get("quant") or "").lower())
        cur = best.get(key)
        if cur is None or rank(d) >= rank(cur):
            best[key] = d
    return [{k: v for k, v in d.items() if k != "_src"} for d in best.values()]


def render_document(directory: Path | None = None) -> str:
    """The Markdown table wrapped as a standalone, self-describing file —
    title + a 'generated, don't hand-edit' note. Used when writing to --out so
    the committed artifact explains its own provenance."""
    table = render_markdown(directory)
    if not table:
        return ""
    return ("# Model reports — DGX Spark / GB10\n\n"
            "_Generated by `spark llm reports` from the per-model JSON reports "
            "alongside this file — do not hand-edit. Regenerate after "
            "`spark llm bench`/`probe --save`._\n\n"
            + table + "\n")


def render_markdown(directory: Path | None = None) -> str:
    """Render all reports as a Markdown table, fastest model first."""
    rows = _dedupe(collect(directory))
    if not rows:
        return ""
    rows.sort(key=lambda d: (d.get("speed") or {}).get("tps_mean") or -1, reverse=True)
    out = ["| Model | Quant | Source | Footprint | tok/s | Capability | Updated |",
           "|-------|-------|--------|-----------|-------|------------|---------|"]
    for d in rows:
        speed = d.get("speed") or {}
        cap = d.get("capability") or {}
        tps = speed.get("tps_mean")
        tps_s = f"{tps:.1f}" if isinstance(tps, (int, float)) else "—"
        out.append("| {m} | {q} | {src} | {fp} | {tps} | {cap} | {up} |".format(
            m=d.get("model") or "—", q=d.get("quant") or "—",
            src=d.get("source_repo") or "—", fp=d.get("footprint") or "—",
            tps=tps_s, cap=cap.get("summary") or "—", up=d.get("updated") or "—"))
    return "\n".join(out)
